var dictionary = {
  "1": "Glenfarclas",
  "2": "Glenlivet",
  "3": "Bowmore",
  "4": "Highland Park",
  "5": "Auchentoshan",
  "6": "Glen Deveron (Macduff)",
  "7": "Longmorn",
  "8": "Tamdhu",
  "9": "Glen Grant",
  "10": "Bunnahabhain",
  "11": "Tomatin",
  "12": "Benriach",
  "13": "Dalmore",
  "14": "Talisker",
  "15": "Glenfiddich",
  "16": "Glenturret",
  "17": "Scapa",
  "18": "Inchgower",
  "19": "Glen Garioch",
  "20": "Inverleven",
  "21": "Glenglassaugh",
  "22": "Glenkinchie",
  "23": "Bruichladdich",
  "24": "Macallan",
  "25": "Rosebank",
  "26": "Clynelish",
  "27": "Springbank",
  "28": "Tullibardine",
  "29": "Laphroaig",
  "30": "Glenrothes",
  "31": "Isle of Jura",
  "32": "Edradour",
  "33": "Ardbeg",
  "34": "Tamnavulin",
  "35": "Glen Moray",
  "36": "Benrinnes",
  "37": "Cragganmore",
  "38": "Caperdonich",
  "39": "Linkwood",
  "40": "Balvenie",
  "41": "Dailuaine",
  "42": "Ledaig (Tobermory)",
  "43": "Port Ellen",
  "44": "Craigellachie",
  "45": "Dallas Dhu",
  "46": "Glenlossie",
  "47": "Benromach",
  "48": "Balmenach",
  "49": "St. Magdalene",
  "50": "Bladnoch",
  "51": "Bushmills",
  "52": "Old Pulteney",
  "53": "Caol Ila",
  "54": "Aberlour",
  "55": "Royal Brackla",
  "56": "Coleburn",
  "57": "Glen Mhor",
  "58": "Strathisla",
  "59": "Teaninich",
  "60": "Aberfeldy",
  "61": "Brora",
  "62": "Glenlochy",
  "63": "Glentauchers",
  "64": "Mannochmore",
  "65": "Imperial",
  "66": "Ardmore",
  "67": "Banff",
  "68": "Blair Athol",
  "69": "Glen Albyn",
  "70": "Balblair",
  "71": "Glenburgie",
  "72": "Miltonduff",
  "73": "Aultmore",
  "74": "North Port",
  "75": "Glenury-Royal",
  "76": "Mortlach",
  "77": "Glen Ord",
  "78": "Ben Nevis",
  "79": "Deanston",
  "80": "Glen Spey",
  "81": "Glen Keith",
  "82": "Glencadam",
  "83": "Convalmore",
  "84": "Glendullan",
  "85": "Glen Elgin",
  "86": "Glenesk",
  "87": "Millburn",
  "88": "Speyburn",
  "89": "Tomintoul",
  "90": "Pittyvaich",
  "91": "Dufftown",
  "92": "Lochside",
  "93": "Glen Scotia",
  "94": "Old Fettercairn",
  "95": "Auchroisk (Singleton)",
  "96": "Glendronach",
  "97": "Littlemill",
  "98": "Lomond (Inverleven)",
  "99": "Glenugie",
  "100": "Strathmill",
  "101": "Knockando",
  "102": "Dalwhinnie",
  "103": "Royal Lochnagar",
  "104": "Glencraig (Glenburgie)",
  "105": "Tormore",
  "106": "Cardhu",
  "107": "Glenallachie",
  "108": "Allt-a-Bhainne",
  "109": "Mosstowie (Miltonduff)",
  "110": "Oban",
  "111": "Lagavulin",
  "112": "Loch Lomond (Inchmurrin)",
  "113": "Braes of Glenlivet (Braeval)",
  "114": "Longrow (Springbank)",
  "115": "An Cnoc (Knockdhu)",
  "116": "Yoichi",
  "117": "Cooley Distillery (unpeated)",
  "118": "Cooley Distillery (peated)",
  "119": "Yamazaki",
  "120": "Hakushu",
  "121": "Isle of Arran",
  "122": "Croftengea (Loch Lomond)",
  "123": "Glengoyne",
  "124": "Miyagikyo",
  "125": "Glenmorangie",
  "126": "Hazelburn (Springbank)",
  "127": "Port Charlotte (Bruichladdich)",
  "128": "Penderyn",
  "129": "Kilchoman",
  "130": "Chichibu",
  "131": "Hanyu",
  "132": "Karuizawa",
  "G1": "North British",
  "G2": "Carsebridge",
  "G3": "Caledonian",
  "G4": "Cameronbridge",
  "G5": "Invergordon",
  "G6": "Port Dundas",
  "G7": "Girvan",
  "G8": "Cambus",
  "G9": "Loch Lomond",
  "G10": "Strathclyde",
  "G11": "Nikka Coffey Grain",
  "G12": "Nikka Coffey Malt",
  "G13": "Chita",
  "G14": "Dumbarton",
  "B1": "Heaven Hill",
  "B2": "Bernheim",
  "B3": "Rock Town"
};

var caskIdExpression = /CASK NO\. (\w{1,3})\.\d{1,3}/;
var on_product_collection_page = document.getElementsByClassName("template-collection").length > 0;
var on_product_details_page = document.getElementsByClassName("template-product").length > 0;

if (on_product_collection_page) {
  var allProducts = document.getElementsByClassName("search-title");
  if (allProducts.length > 0) {
    for (var i=0; i < allProducts.length; i++) {
      var productSpan = allProducts[i];
      var matchArray = caskIdExpression.exec(productSpan.innerText);
      var distilleryName = dictionary.hasOwnProperty(RegExp.$1) ? dictionary[RegExp.$1] : "Unknown";
      productSpan.innerText = "Distillery: " + distilleryName;
    }
  }
}
else if (on_product_details_page) {
  var productBanner = document.getElementsByClassName("page-title")[0];
  var matchArray = caskIdExpression.exec(productBanner.innerText);
  var distilleryName = dictionary.hasOwnProperty(RegExp.$1) ? dictionary[RegExp.$1] : "Unknown";
  var distilleryH4 = document.createElement("h4");
  productBanner.parentNode.insertBefore(distilleryH4, productBanner.nextSibling);
  distilleryH4.innerText = "(" + distilleryName + ")";
}
